package cli

import (
	"errors"
	"fmt"

	"github.com/spf13/cobra"

	"github.com/bombfork/releaser/internal/adapter"
	"github.com/bombfork/releaser/internal/adapters"
	"github.com/bombfork/releaser/internal/config"
	"github.com/bombfork/releaser/internal/github"
	"github.com/bombfork/releaser/internal/release"
)

func newReleaseCommand() *cobra.Command {
	var dryRun bool

	cmd := &cobra.Command{
		Use:   "release",
		Short: "Cut a release of the current project",
		Long: `Interactive when run locally, non-interactive when run in CI by the
generated GitHub Actions workflows. Idempotent: re-running a partially
completed release only performs the steps that are missing.

With --dry-run, print the release plan (current version, commits to be
included, computed next version) and exit without modifying anything.

Subcommands ` + "`prepare`" + ` and ` + "`publish`" + ` drive the two halves of the release
pipeline; the workflows generated by ` + "`releaser generate`" + ` invoke them.`,
		RunE: func(cmd *cobra.Command, args []string) error {
			repoRoot, err := cmd.Flags().GetString(RepoRootFlag)
			if err != nil {
				return err
			}
			if dryRun {
				return runReleaseDryRun(cmd, repoRoot)
			}
			return errors.New("release: specify a subcommand (prepare/publish) or use --dry-run")
		},
	}

	cmd.Flags().BoolVar(&dryRun, "dry-run", false, "Print the planned release without performing any side effects")
	cmd.AddCommand(newReleasePrepareCommand())

	return cmd
}

func runReleaseDryRun(cmd *cobra.Command, repoRoot string) error {
	cfg, ad, err := loadConfigAndAdapter(repoRoot)
	if err != nil {
		return err
	}
	plan, err := release.BuildPlan(repoRoot, *cfg, ad)
	if err != nil {
		return fmt.Errorf("build plan: %w", err)
	}
	if _, err := fmt.Fprint(cmd.OutOrStdout(), plan.String()); err != nil {
		return fmt.Errorf("write plan: %w", err)
	}
	return nil
}

func newReleasePrepareCommand() *cobra.Command {
	return &cobra.Command{
		Use:   "prepare",
		Short: "Maintain the pending-release pull request",
		Long: `Compute the next release version from commits since the latest tag,
apply the version-file bump on the configured side branch
(release.branch_name, default releaser/pending-release), force-push
that branch, and open or update the matching pull request.

Idempotent: re-running on the same default-branch HEAD produces an
equivalent end state. When no commits since the latest release warrant
a version bump, prepare exits cleanly with no side effects.`,
		RunE: func(cmd *cobra.Command, args []string) error {
			repoRoot, err := cmd.Flags().GetString(RepoRootFlag)
			if err != nil {
				return err
			}
			return runReleasePrepare(cmd, repoRoot)
		},
	}
}

func runReleasePrepare(cmd *cobra.Command, repoRoot string) error {
	cfg, ad, err := loadConfigAndAdapter(repoRoot)
	if err != nil {
		return err
	}
	tp, err := github.DefaultTokenProvider()
	if err != nil {
		return fmt.Errorf("resolve token provider: %w", err)
	}
	ghClient, err := github.NewClientFromTokenProvider(tp)
	if err != nil {
		return fmt.Errorf("build github client: %w", err)
	}
	return release.Prepare(cmd.Context(), repoRoot, release.PrepareInputs{
		Config:        *cfg,
		Adapter:       ad,
		GitHubClient:  ghClient,
		TokenProvider: tp,
	})
}

// loadConfigAndAdapter loads the on-disk configuration and resolves its
// adapter. Used by every release subcommand.
func loadConfigAndAdapter(repoRoot string) (*config.Config, adapter.Adapter, error) {
	cfg, err := config.Load(repoRoot)
	if err != nil {
		return nil, nil, fmt.Errorf("load configuration: %w", err)
	}
	registry := adapters.DefaultRegistry()
	ad, ok := registry.ByName(cfg.Adapter)
	if !ok {
		return nil, nil, fmt.Errorf("unknown adapter %q in configuration", cfg.Adapter)
	}
	return cfg, ad, nil
}
